-- drop SCHEMA if exists PRENOTAZIONE_ALBERGHIERA;
create SCHEMA PRENOTAZIONE_ALBERGHIERA; 
USE PRENOTAZIONE_ALBERGHIERA;

-- DROP TABLE IF EXISTS OSPITE;
CREATE TABLE OSPITE (
ID_OSPITE int
, NOME VARCHAR (12)	
, COGNOME varchar(20)
, DOCUMENTO	varchar(20)
, NUM_DOCUMENTO int
, RECAPITO INT
, RESIDENZA VARCHAR (40)
, constraint PK_OSPITE primary key (ID_OSPITE)
);

-- DROP TABLE IF EXISTS SERVIZIO;
create table SERVIZIO (
ID_SERVIZIO int	
, TIPOLOGIA varchar(30)
, PREZZO int
, constraint PK_SERVIZIO primary key (ID_SERVIZIO)
);

-- DROP TABLE IF EXISTS CAMERA;
CREATE TABLE CAMERA (
ID_CAMERA int	
, TIPOLOGIA	varchar(30)
, ID_SERVIZIO INT
, ID_ALBERGO INT	
, PREZZO_A_NOTTE INT
, constraint PK_CAMERA primary key (ID_CAMERA)
);

ALTER table CAMERA
ADD constraint FK_SERVIZIO_CAMERA foreign key (ID_SERVIZIO) references SERVIZIO (ID_SERVIZIO)
;

ALTER table CAMERA
DROP column ID_ALBERGO
;

-- DROP TABLE IF EXISTS ALBERGO;
CREATE TABLE ALBERGO (
ID_ALBERGO int	
, NOME varchar(15)	
, INDIRIZZO varchar(40)
, constraint PK_ALBERGO primary key (ID_ALBERGO)
);

ALTER TABLE ALBERGO
ADD column ID_CAMERA int
;

ALTER TABLE ALBERGO
ADD constraint FK_CAMERA_ALBERGO foreign key (ID_CAMERA) references CAMERA (ID_CAMERA)
;

-- DROP TABLE IF EXISTS PRENOTAZIONE;
create table PRENOTAZIONE (
ID_PRENOTAZIONE	INT
, ID_CLIENTE INT
, DATA_INIZIO_PRENOTAZIONE date	
, DATA_FINE_PRENOTAZIONE date	
, PREZZO_FINALE int
, constraint PK_PRENOTAZIONE primary key (ID_PRENOTAZIONE)
);

ALTER table PRENOTAZIONE 
RENAME column ID_CLIENTE to ID_OSPITE
;

ALTER table PRENOTAZIONE 
add column ID_CAMERA int
;

ALTER table PRENOTAZIONE 
ADD constraint FK_OSPITE_PRENOTAZIONE foreign key (ID_OSPITE) references OSPITE (ID_OSPITE)
;

ALTER table PRENOTAZIONE 
ADD constraint FK_CAMERA_PRENOTAZIONE foreign key (ID_CAMERA) references CAMERA (ID_CAMERA)
;






