-- DROP SCHEMA IF EXISTS NOLEGGIO_AUTO;
create schema NOLEGGIO_AUTO;
USE NOLEGGIO_AUTO;

-- DROP TABLE IF EXISTS CLIENTE;
CREATE table CLIENTE (
ID_CLIENTE int
, NOME varchar(15)	
, COGNOME varchar(20)
, CELLULARE	int
, RESIDENZA	varchar(50)
, ID_PRENOTAZIONE int
, constraint PK_CLIENTE primary key (ID_CLIENTE)
);
ALTER TABLE CLIENTE
ADD NUMERO_PATENTE char(10);

ALTER TABLE CLIENTE
ADD constraint FK_PRENOTAZIONE_CLIENTE foreign key (ID_PRENOTAZIONE) references PRENOTAZIONE (ID_PRENOTAZIONE);

-- DROP TABLE IF EXISTS PRENOTAZIONE;
CREATE table PRENOTAZIONE (
ID_PRENOTAZIONE int	
, ID_CLIENTE int	
, ID_AUTO INT
, constraint PK_PRENOTAZIONE primary key (ID_PRENOTAZIONE)
);

ALTER table PRENOTAZIONE
 ADD DATA_PRENOTAZIONE date;

ALTER table PRENOTAZIONE
ADD constraint FK_CLIENTE_PRENOTAZIONE foreign key (ID_CLIENTE) references CLIENTE (ID_CLIENTE)
, ADD constraint FK_AUTO_PRENOTAZIONE foreign key (ID_AUTO) references AUTO (ID_AUTO)
;

-- DROP TABLE IF EXISTS AUTO;
create TABLE AUTO (
ID_AUTO int	
, MODELLO varchar(40)	
, TARGA CHAR(7)
, KM_PERCORSI int
, EVENTUALI_DANNI_RIPORTATI varchar(100)
, constraint PK_AUTO primary key (ID_AUTO)
);

ALTER TABLE AUTO
ADD ID_LUOGO int
;

ALTER TABLE AUTO
ADD constraint FK_LUOGO_AUTO foreign key (ID_LUOGO) references LUOGO (ID_LUOGO)
;

-- DROP TABLE IF EXISTS LUOGO;
create table LUOGO (
ID_LUOGO int	
, NOME_LUOGO varchar(50)
, ID_AUTO int
, constraint PK_LUOGO primary key (ID_LUOGO)
);

ALTER TABLE LUOGO
ADD constraint FK_AUTO_LUOGO foreign key (ID_AUTO) references AUTO (ID_AUTO)
;
 
-- DROP TABLE IF EXISTS NOLEGGIO;
CREATE TABLE NOLEGGIO (
ID_NOLEGGIO int
, ID_CLIENTE int
, ID_PRENOTAZIONE int
, ID_AUTO int
, constraint PK_NOLEGGIO primary key (ID_NOLEGGIO)
);

ALTER table NOLEGGIO
ADD DATA_INIZIO_NOLEGGIO date
, ADD DATA_FINE_NOLEGGIO date
, ADD COSTO_FINALE int
;

ALTER TABLE NOLEGGIO
ADD constraint FK_AUTO_NOLEGGIO foreign key (ID_AUTO) references AUTO (ID_AUTO)
, ADD constraint FK_PRENOTAZIONE_NOLEGGIO foreign key (ID_PRENOTAZIONE) references PRENOTAZIONE (ID_PRENOTAZIONE)
, ADD constraint FK_CLIENTE_NOLEGGIO foreign key (ID_CLIENTE) references CLIENTE (ID_CLIENTE)
;



